package Vista;
import Controlador.Controlador;
import Persistencia.GestorProveedores;
import Persistencia.GestorEntregas;
import Persistencia.GestorPedidos;
import Modelo.Proveedor;
import java.util.List;

public class EstadisticasVista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EstadisticasVista.class.getName());

    /**
     * Creates new form EstadisticasVista
     */
    // Componentes de fechas
    private com.github.lgooddatepicker.components.DatePicker fechaInicioPicker = new com.github.lgooddatepicker.components.DatePicker();
    private com.github.lgooddatepicker.components.DatePicker fechaFinPicker = new com.github.lgooddatepicker.components.DatePicker();
    private Controlador controlador = new Controlador(new GestorProveedores(), new GestorEntregas(), new GestorPedidos());
    private javax.swing.JList<String> listProveedores = new javax.swing.JList<>();
    private javax.swing.JScrollPane scrollProveedores = new javax.swing.JScrollPane(listProveedores);
    public EstadisticasVista() {
        initComponents();
        areaResultados.setEditable(false);
        panelFechaInicio.setLayout(new java.awt.BorderLayout());
        panelFechaInicio.add(fechaInicioPicker, java.awt.BorderLayout.CENTER);
        panelFechaFinal.setLayout(new java.awt.BorderLayout());
        panelFechaFinal.add(fechaFinPicker, java.awt.BorderLayout.CENTER);
        listProveedores.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        panelProveedores.setLayout(new java.awt.BorderLayout());
        panelProveedores.add(scrollProveedores, java.awt.BorderLayout.CENTER);
        cargarProveedoresList();
        
        getContentPane().setBackground(new java.awt.Color(30, 80, 120));
        setTitle("PaperDesk — Estadísticas");
        
        java.awt.Font fuenteLabel = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13);
        java.awt.Color colorBlanco = java.awt.Color.WHITE;

        jLabel3.setForeground(colorBlanco); 
        jLabel3.setFont(fuenteLabel);
        jLabel4.setForeground(colorBlanco);  
        jLabel4.setFont(fuenteLabel);
        jLabel8.setForeground(colorBlanco);  
        jLabel8.setFont(fuenteLabel);
        jLabel1.setForeground(colorBlanco);  
        jLabel1.setFont(fuenteLabel);
        jLabel2.setForeground(colorBlanco);  
        jLabel2.setFont(fuenteLabel);

        botonBuscar.setBackground(new java.awt.Color(39, 174, 96));
        botonBuscar.setForeground(java.awt.Color.WHITE);
        botonBuscar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        botonBuscar.setFocusPainted(false);
        botonBuscar.setBorderPainted(false);
        botonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        areaResultados.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        areaResultados.setBackground(new java.awt.Color(20, 60, 100));
        areaResultados.setForeground(colorBlanco);
        areaResultados.setMargin(new java.awt.Insets(10, 10, 10, 10));

        javax.swing.JLabel labelTitulo = new javax.swing.JLabel("Estadísticas");
        labelTitulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));
        labelTitulo.setForeground(java.awt.Color.WHITE);
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelTitulo, java.awt.BorderLayout.NORTH);
}

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaResultados = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelFechaInicio = new javax.swing.JPanel();
        panelFechaFinal = new javax.swing.JPanel();
        panelProveedores = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botonBuscar.setText("Ver estadisticas");
        botonBuscar.addActionListener(this::botonBuscarActionPerformed);

        areaResultados.setColumns(20);
        areaResultados.setRows(5);
        jScrollPane1.setViewportView(areaResultados);

        jLabel3.setText("Fecha fin:");

        jLabel4.setText("Fecha inicio:");

        jLabel8.setText("Proveedor");

        javax.swing.GroupLayout panelFechaInicioLayout = new javax.swing.GroupLayout(panelFechaInicio);
        panelFechaInicio.setLayout(panelFechaInicioLayout);
        panelFechaInicioLayout.setHorizontalGroup(
            panelFechaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        panelFechaInicioLayout.setVerticalGroup(
            panelFechaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelFechaFinalLayout = new javax.swing.GroupLayout(panelFechaFinal);
        panelFechaFinal.setLayout(panelFechaFinalLayout);
        panelFechaFinalLayout.setHorizontalGroup(
            panelFechaFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        panelFechaFinalLayout.setVerticalGroup(
            panelFechaFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelProveedoresLayout = new javax.swing.GroupLayout(panelProveedores);
        panelProveedores.setLayout(panelProveedoresLayout);
        panelProveedoresLayout.setHorizontalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        panelProveedoresLayout.setVerticalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel1.setText("Mantener ctrl para");

        jLabel2.setText("seleccionar más de uno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(panelFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(panelFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(panelProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(77, 77, 77)
                        .addComponent(botonBuscar)))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        if(fechaInicioPicker.getDate() == null || fechaFinPicker.getDate() == null){
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona ambas fechas");
            return;
        }
        String fechaInicio = fechaInicioPicker.getDate().toString();
        String fechaFin = fechaFinPicker.getDate().toString();
        if(fechaInicio.compareTo(fechaFin) > 0){
            javax.swing.JOptionPane.showMessageDialog(this, "La fecha de inicio no puede ser mayor que la fecha fin");
            return;
        }
        List<String> seleccionados = listProveedores.getSelectedValuesList();
        List<String> idsProveedores = new java.util.ArrayList<>();
        for(String s : seleccionados){
            idsProveedores.add(s.split(" - ")[0]);
        }
        String resultado = controlador.obtenerEstadisticasRango(fechaInicio, fechaFin, idsProveedores);
        areaResultados.setText(resultado);
    }//GEN-LAST:event_botonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void cargarProveedoresList(){
        List<Proveedor> lista = controlador.obtenerListaProveedores();
        String[] nombres = new String[lista.size()];
        for(int i = 0; i < lista.size(); i++){
            nombres[i] = lista.get(i).getId() + " - " + lista.get(i).getNombre();
        }
        listProveedores.setListData(nombres);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EstadisticasVista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaResultados;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelFechaFinal;
    private javax.swing.JPanel panelFechaInicio;
    private javax.swing.JPanel panelProveedores;
    // End of variables declaration//GEN-END:variables
}
