package Vista;

public class MenuPrincipalVista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalVista.class.getName());

    /**
     * Creates new form MenuPrincipalVista
     */
    public MenuPrincipalVista() {
        initComponents();
        // Título de la ventana
    setTitle("PaperDesk — Gestión de Pedidos");
    
    // Color de fondo
    getContentPane().setBackground(new java.awt.Color(30, 80, 120));
    
    // Estilo botón 1 - Gestionar Proveedores
    estilizarBoton(jButton1);
    estilizarBoton(jButton2);
    estilizarBoton(jButton3);
    estilizarBoton(jButton4);
    estilizarBoton(jButton5);
    
    // Panel superior con título  ← AGREGAR AQUÍ
    javax.swing.JPanel panelTitulo = new javax.swing.JPanel();
    panelTitulo.setBackground(new java.awt.Color(20, 60, 100));
    panelTitulo.setPreferredSize(new java.awt.Dimension(600, 80));

    javax.swing.JLabel labelTitulo = new javax.swing.JLabel("PaperDesk");
    labelTitulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 36));
    labelTitulo.setForeground(new java.awt.Color(255, 255, 255));

    javax.swing.JLabel labelSubtitulo = new javax.swing.JLabel("Gestión de Pedidos");
    labelSubtitulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    labelSubtitulo.setForeground(new java.awt.Color(180, 210, 240));

    panelTitulo.setLayout(new java.awt.GridLayout(2, 1));
    labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
labelSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    panelTitulo.add(labelTitulo);
    panelTitulo.add(labelSubtitulo);

    // En lugar de agregar al ContentPane directamente, 
// usamos un JPanel contenedor
javax.swing.JPanel contenedor = new javax.swing.JPanel(new java.awt.BorderLayout());
contenedor.setBackground(new java.awt.Color(30, 80, 120));
contenedor.add(panelTitulo, java.awt.BorderLayout.NORTH);

// Mover los botones al centro
javax.swing.JPanel panelBotones = new javax.swing.JPanel(new java.awt.GridLayout(5, 1, 0, 20));
panelBotones.setBackground(new java.awt.Color(30, 80, 120));
panelBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(60, 400, 60, 400));
panelBotones.add(jButton1);
panelBotones.add(jButton2);
panelBotones.add(jButton4);
panelBotones.add(jButton3);
panelBotones.add(jButton5);

contenedor.add(panelBotones, java.awt.BorderLayout.CENTER);
setContentPane(contenedor);
    
    }

// Método para estilizar botones
private void estilizarBoton(javax.swing.JButton boton) {
    boton.setBackground(new java.awt.Color(255, 255, 255));
    boton.setForeground(new java.awt.Color(30, 80, 120));
    boton.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    boton.setFocusPainted(false);
    boton.setBorderPainted(false);
    boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    boton.setPreferredSize(new java.awt.Dimension(250, 45));
}

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Gestionar Proveedores");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Registrar Pedido");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Ver Historial");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Registrar Entrega");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Ver Estadisticas");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(451, 451, 451)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(506, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addComponent(jButton2)
                .addGap(27, 27, 27)
                .addComponent(jButton4)
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addGap(29, 29, 29)
                .addComponent(jButton5)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new GestionProveedorVista().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new RegistrarPedidoVista().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new RegistrarEntregaVista().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new HistorialVista().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new EstadisticasVista().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipalVista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
