package Vista;
import Controlador.Controlador;
import Persistencia.GestorProveedores;
import Persistencia.GestorEntregas;
import Persistencia.GestorPedidos;
import Modelo.Pedido;
import java.util.List;
import javax.swing.JOptionPane;
import com.github.lgooddatepicker.components.DatePicker;
import java.time.LocalDate;
import com.github.lgooddatepicker.components.TimePicker;

public class RegistrarEntregaVista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrarEntregaVista.class.getName());

    /**
     * Creates new form RegistrarEntregaVista
     */
    private Controlador controlador = new Controlador(new GestorProveedores(), new GestorEntregas(), new GestorPedidos());
    public RegistrarEntregaVista() {
        initComponents();
        panelFecha.setLayout(new java.awt.BorderLayout());
        panelFecha.add(fechaPicker, java.awt.BorderLayout.CENTER);
        panelHora.setLayout(new java.awt.BorderLayout());
        panelHora.add(horaPicker, java.awt.BorderLayout.CENTER);
        campoId.setText(controlador.generarIdEntrega());
        campoId.setEditable(false);
        cargarPedidosCombo();

        getContentPane().setBackground(new java.awt.Color(30, 80, 120));
        setTitle("PaperDesk — Registrar Entrega");

        java.awt.Font fuenteLabel = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13);
        java.awt.Color colorBlanco = java.awt.Color.WHITE;

        Id.setForeground(colorBlanco);
        Id.setFont(fuenteLabel);
        jLabel1.setForeground(colorBlanco);
        jLabel1.setFont(fuenteLabel);
        jLabel2.setForeground(colorBlanco);
        jLabel2.setFont(fuenteLabel);
        jLabel3.setForeground(colorBlanco);
        jLabel3.setFont(fuenteLabel);
        jLabel4.setForeground(colorBlanco);
        jLabel4.setFont(fuenteLabel);
        jLabel6.setForeground(colorBlanco);
        jLabel6.setFont(fuenteLabel);

        botonRegistrarEntrega.setBackground(new java.awt.Color(39, 174, 96));
        botonRegistrarEntrega.setForeground(java.awt.Color.WHITE);
        botonRegistrarEntrega.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        botonRegistrarEntrega.setFocusPainted(false);
        botonRegistrarEntrega.setBorderPainted(false);
        botonRegistrarEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.JLabel labelTitulo = new javax.swing.JLabel("Registrar Entrega");
        labelTitulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));
        labelTitulo.setForeground(java.awt.Color.WHITE);
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelTitulo, java.awt.BorderLayout.NORTH);
        
        comboPedido.setEditable(true);
        javax.swing.JTextField editor = (javax.swing.JTextField) comboPedido.getEditor().getEditorComponent();
        editor.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent e) {
        String texto = editor.getText().toLowerCase();
        comboPedido.removeAllItems();
        List<Pedido> lista = controlador.obtenerListaPedidos();
        for(Pedido pedido : lista){
            if(pedido.getEstado().equals("Pendiente") || pedido.getEstado().equals("Incompleto")){
                String nombreProveedor = controlador.obtenerListaProveedores().stream()
                    .filter(p -> p.getId().equals(pedido.getIdProveedor()))
                    .findFirst()
                    .map(p -> p.getNombre())
                    .orElse(pedido.getIdProveedor());
                String item = pedido.getId() + " - " + nombreProveedor + " - $" + pedido.getValorTotal();
                if(item.toLowerCase().contains(texto)){
                    comboPedido.addItem(item);
                }
            }
        }
        editor.setText(texto);
        comboPedido.showPopup();
    }
});
    }
    private DatePicker fechaPicker = new DatePicker();
    private TimePicker horaPicker = new TimePicker();    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoId = new javax.swing.JTextField();
        comboPedido = new javax.swing.JComboBox<>();
        campoValorParcial = new javax.swing.JTextField();
        botonRegistrarEntrega = new javax.swing.JButton();
        panelFecha = new javax.swing.JPanel();
        panelHora = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Fecha:");

        jLabel3.setText("Hora:");

        jLabel4.setText("Pedido:");

        Id.setText("ID:");

        jLabel6.setText("Valor Parcial:");

        comboPedido.addActionListener(this::comboPedidoActionPerformed);

        botonRegistrarEntrega.setText("Registrar");
        botonRegistrarEntrega.addActionListener(this::botonRegistrarEntregaActionPerformed);

        javax.swing.GroupLayout panelFechaLayout = new javax.swing.GroupLayout(panelFecha);
        panelFecha.setLayout(panelFechaLayout);
        panelFechaLayout.setHorizontalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );
        panelFechaLayout.setVerticalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelHoraLayout = new javax.swing.GroupLayout(panelHora);
        panelHora.setLayout(panelHoraLayout);
        panelHoraLayout.setHorizontalGroup(
            panelHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelHoraLayout.setVerticalGroup(
            panelHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(Id)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(campoValorParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(506, 506, 506))
            .addGroup(layout.createSequentialGroup()
                .addGap(528, 528, 528)
                .addComponent(botonRegistrarEntrega)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoValorParcial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Id)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addGap(31, 31, 31)
                .addComponent(botonRegistrarEntrega)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarEntregaActionPerformed
        String id = campoId.getText();
        String idPedido = comboPedido.getSelectedItem().toString().split(" ")[0];
        LocalDate fechaEntrega = fechaPicker.getDate();
        if(fechaEntrega == null){
            JOptionPane.showMessageDialog(this, "Selecciona una fecha");
            return;
        }
        List<Pedido> pedidos = controlador.obtenerListaPedidos();
        for(Pedido pedidito : pedidos){
            if(pedidito.getId().equals(idPedido)){
                LocalDate fechaPedido = LocalDate.parse(pedidito.getFecha());
                if(fechaEntrega.isBefore(fechaPedido)){
                    JOptionPane.showMessageDialog(this, "La fecha de entrega no puede ser anterior a la fecha del pedido (" + pedidito.getFecha() + ")");
                    return;
                }
            }
        }
        String fechaStr = fechaEntrega.toString();
        if(horaPicker.getTime() == null){
            JOptionPane.showMessageDialog(this, "Selecciona una hora");
            return;
        }
        String hora = horaPicker.getTime().toString();
        if(campoValorParcial.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "El valor parcial no puede estar vacío");
            return;
        }
        double valorParcial = Double.parseDouble(campoValorParcial.getText());
        String resultado = controlador.registrarEntrega(id, idPedido, fechaStr, hora, valorParcial);
        JOptionPane.showMessageDialog(this, resultado);
        campoId.setText(controlador.generarIdEntrega());
        comboPedido.removeAllItems();
        cargarPedidosCombo();
    }//GEN-LAST:event_botonRegistrarEntregaActionPerformed

    private void comboPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarPedidosCombo(){
        List<Pedido> lista = controlador.obtenerListaPedidos();
        for(Pedido pedido : lista){
            if(pedido.getEstado().equals("Pendiente") || pedido.getEstado().equals("Incompleto")){
                String nombreProveedor = controlador.buscarPorIdProveedor(pedido.getIdProveedor()).isEmpty() ? 
                     pedido.getIdProveedor() : 
                    controlador.obtenerListaProveedores().stream()
                    .filter(p -> p.getId().equals(pedido.getIdProveedor()))
                    .findFirst()
                    .map(p -> p.getNombre())
                    .orElse(pedido.getIdProveedor());
                    comboPedido.addItem(pedido.getId() + " - " + nombreProveedor + " - $" + pedido.getValorTotal());
            }
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistrarEntregaVista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Id;
    private javax.swing.JButton botonRegistrarEntrega;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoValorParcial;
    private javax.swing.JComboBox<String> comboPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelFecha;
    private javax.swing.JPanel panelHora;
    // End of variables declaration//GEN-END:variables
}
