package Vista;
import Modelo.Pedido;
import Controlador.Controlador;
import Persistencia.GestorProveedores;
import Persistencia.GestorEntregas;
import Persistencia.GestorPedidos;
import Modelo.Pedido;
import java.util.List;
import javax.swing.JOptionPane;
import com.github.lgooddatepicker.components.DatePicker;
import java.time.LocalDate;

public class RegistrarEntregaVista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrarEntregaVista.class.getName());

    /**
     * Creates new form RegistrarEntregaVista
     */
    private Controlador controlador = new Controlador(new GestorProveedores(), new GestorEntregas(), new GestorPedidos());
    public RegistrarEntregaVista() {
        initComponents();
        panelFecha.setLayout(new java.awt.BorderLayout());
        panelFecha.add(fechaPicker, java.awt.BorderLayout.CENTER);
        campoId.setText(controlador.generarIdEntrega());
        campoId.setEditable(false);
        cargarPedidosCombo();
    }
    private DatePicker fechaPicker = new DatePicker();
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoId = new javax.swing.JTextField();
        comboPedido = new javax.swing.JComboBox<>();
        campoHora = new javax.swing.JTextField();
        campoValorParcial = new javax.swing.JTextField();
        botonRegistrarEntrega = new javax.swing.JButton();
        panelFecha = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Fecha:");

        jLabel3.setText("Hora:");

        jLabel4.setText("Pedido:");

        Id.setText("ID:");

        jLabel6.setText("Valor Parcial:");

        comboPedido.addActionListener(this::comboPedidoActionPerformed);

        botonRegistrarEntrega.setText("Registrar");
        botonRegistrarEntrega.addActionListener(this::botonRegistrarEntregaActionPerformed);

        javax.swing.GroupLayout panelFechaLayout = new javax.swing.GroupLayout(panelFecha);
        panelFecha.setLayout(panelFechaLayout);
        panelFechaLayout.setHorizontalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );
        panelFechaLayout.setVerticalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Id)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(3, 3, 3))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3))
                            .addGap(95, 95, 95)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoValorParcial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonRegistrarEntrega)
                        .addGap(145, 145, 145)))
                .addGap(375, 375, 375))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id)
                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(panelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoValorParcial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonRegistrarEntrega)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarEntregaActionPerformed
        String id = campoId.getText();
        String idPedido = comboPedido.getSelectedItem().toString().split(" ")[0];

        LocalDate fechaEntrega = fechaPicker.getDate();
        if(fechaEntrega == null){
            JOptionPane.showMessageDialog(this, "Selecciona una fecha");
            return;
        }

        // Validar que la fecha de entrega no sea anterior a la fecha del pedido
        List<Pedido> pedidos = controlador.obtenerListaPedidos();
        for(Pedido pedidito : pedidos){
            if(pedidito.getId().equals(idPedido)){
                LocalDate fechaPedido = LocalDate.parse(pedidito.getFecha());
                if(fechaEntrega.isBefore(fechaPedido)){
                    JOptionPane.showMessageDialog(this, "La fecha de entrega no puede ser anterior a la fecha del pedido (" + pedidito.getFecha() + ")");
                    return;
                }
            }
        }

        String fechaStr = fechaEntrega.toString();
        String hora = campoHora.getText();
        double valorParcial = Double.parseDouble(campoValorParcial.getText());
        String resultado = controlador.registrarEntrega(id, idPedido, fechaStr, hora, valorParcial);
        JOptionPane.showMessageDialog(this, resultado);
        campoId.setText(controlador.generarIdEntrega());
    }//GEN-LAST:event_botonRegistrarEntregaActionPerformed

    private void comboPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarPedidosCombo(){
        List<Pedido> lista = controlador.obtenerListaPedidos();
        for(Pedido pedido : lista){
            if(pedido.getEstado().equals("Pendiente") || pedido.getEstado().equals("Incompleto")){
                String nombreProveedor = controlador.buscarPorIdProveedor(pedido.getIdProveedor()).isEmpty() ? 
                     pedido.getIdProveedor() : 
                    controlador.obtenerListaProveedores().stream()
                    .filter(p -> p.getId().equals(pedido.getIdProveedor()))
                    .findFirst()
                    .map(p -> p.getNombre())
                    .orElse(pedido.getIdProveedor());
                    comboPedido.addItem(pedido.getId() + " - " + nombreProveedor + " - $" + pedido.getValorTotal());
            }
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistrarEntregaVista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Id;
    private javax.swing.JButton botonRegistrarEntrega;
    private javax.swing.JTextField campoHora;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoValorParcial;
    private javax.swing.JComboBox<String> comboPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelFecha;
    // End of variables declaration//GEN-END:variables
}
